### ISSUE TITLE
mapillary.com support

### ISSUE THREAD

**Issue by hugobqd** [david-r-edgar/MapSwitcher#13]
Mapillary is a streetview-like.

**Comment by hugobqd** [comment]
Hi! I've done it here : https://github.com/hugobqd/MapSwitcher/commit/e79962d04950384fce93498304c76502ca7af9ef

(I'm not very confortable with github so I don't know if that is the correct process)

**Comment by david-r-edgar** [comment]
Mapillary supported from version 0.4.3, released today. Thanks for your PR!
