### ISSUE TITLE
Yandex maps support

### ISSUE THREAD

**Issue by Joss** [david-r-edgar/MapSwitcher#3]
Could you add yandex maps support?
https://yandex.ru/maps/

API:
https://tech.yandex.com/maps/doc/staticapi/1.x/dg/concepts/input_params-docpage/

**Comment by david-r-edgar** [comment]
Yes, I've been meaning to add yandex for a while. I'll get it sorted in the next release.

**Comment by david-r-edgar** [comment]
Support added in [v0.4.2](https://github.com/david-r-edgar/MapSwitcher/releases/tag/v0.4.2)
