### ISSUE TITLE
f4map.com support

### ISSUE THREAD

**Issue by hugobqd** [david-r-edgar/MapSwitcher#4]
Could you add f4map.com support please?
That the best 3D rendering of openstreetmap as far as I know.
http://demo.f4map.com/

The view may be loaded with a zoom min-value of 16 to have the 3D rendering
Example http://demo.f4map.com/#lat=40.7081861&lon=-74.0097708&zoom=16

Thanks (I really enjoy your extension and use it a lot !)

**Comment by david-r-edgar** [comment]
That's a nice site, thanks for pointing it out! I hadn't seen it before.
Yes, I'll add support for it in the next version.

**Comment by hugobqd** [comment]
Great !

**Comment by david-r-edgar** [comment]
Support added in [v0.4.2](https://github.com/david-r-edgar/MapSwitcher/releases/tag/v0.4.2)
